language: rust
sudo: false

cache:
- cargo

rust:
- stable

before_script:
- cargo install-update -a

script:
- mdbook build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: master